[DATA]
data_set = 'https://raw.githubusercontent.com/5x12/ml-cookbook/master/supplements/data/heart.csv'

[MODEL]
dt_conf = 'conf/random_forest.pkl'

settings = Dynaconf(
    preload = ['plugin_settings.py'],
    settings_file='settings.toml'
)